spring:
  application:
    name: stuti

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
    hibernate:
      naming:
        physical-strategy: prgrms.project.stuti.global.config.SnakeUpperCaseNamingStrategy
